### ISSUE TITLE
Namespace testcase fails to pass

### ISSUE THREAD

**Issue by ghisvail** [pydap/pydap#45] opened 2016-12-28 11:07 UTC
In a fresh checkout of `pydap` in a clean venv, the `namespace` testcase does not pass:
```
======================================================================
FAIL: Test the namespace.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gvaillan/.virtualenvs/pydap/src/pydap/src/pydap/tests/test_pydap.py", line 20, in test_namespace
    pydap.__doc__, "Declare the namespace ``pydap`` here.")
AssertionError: None != 'Declare the namespace ``pydap`` here.'

----------------------------------------------------------------------
Ran 311 tests in 0.582s
```
Indeed, if I manually run:
```python
>>> import pydap
>>> print(pydap.__doc__)
None
```
I am wondering whether this test case is actually useful, beyond increasing the code coverage?

**Comment by jameshiebert** [comment] 2017-01-02 23:05
I cannot reproduces this issue.

```
(env35) hiebert@aether:~/code/pydap$ git pull origin master
X11 forwarding request failed on channel 0
From github.com:pydap/pydap
 * branch            master     -> FETCH_HEAD
Already up-to-date.
(env35) hiebert@aether:~/code/pydap$ nosetests -s pydap.tests.test_pydap
.
Name                        Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------
pydap.py                        1      0      0      0   100%
pydap/tests.py                  1      0      0      0   100%
pydap/tests/test_pydap.py       8      0      0      0   100%
-------------------------------------------------------------
TOTAL                          10      0      0      0   100%
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```

Is it possible that you haven't dev-installed the package before running the tests? Take a look at what we do in the TravisCI config before running the tests. E.g.:

```
pip install -e .[testing,functions,tests]
```

**Comment by ghisvail** [comment] 2017-01-03 14:54
Did you use a *fresh* virtualenv?

Steps:
```
virtualenv --python=python3 ~/.virtualenvs/pydap
cd ~/.virtualenvs/pydap && source ./bin/activate
mkdir src && cd src
git clone https://github.com/pydap/pydap && cd pydap
pip install -e .[testing,functions,tests]
nosetests -s pydap.tests.test_pydap
```
Output:
```
F
======================================================================
FAIL: Test the namespace.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<HOME>/.virtualenvs/pydap/src/pydap/src/pydap/tests/test_pydap.py", line 20, in test_namespace
    pydap.__doc__, "Declare the namespace ``pydap`` here.")
AssertionError: None != 'Declare the namespace ``pydap`` here.'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
```

**Comment by laliberte** [comment] 2017-01-03 16:39
I was able to reproduce on [travis-ci](https://travis-ci.org/laliberte/pydap/jobs/188582962).

**Comment by laliberte** [comment] 2017-01-03 16:59
I've tried a few things but can't seem to make it work. Should we simply remove this [line](https://github.com/pydap/pydap/blob/master/src/pydap/tests/test_pydap.py#L19-L20)? It does not seem to be testing much after all...

**Comment by jameshiebert** [comment] 2017-01-03 19:35
Hrm, OK I'm seeing that now. So I agree with you guys that it doesn't add that much value, but it bugs me because it *should* work. Any ideas why it doesn't?

**Comment by laliberte** [comment] 2017-01-03 19:38
Unfortunately, no. But I agree that it should work. Basic googling brought up nothing. Let's leave it open a bit longer and we might stumble onto something...

**Comment by jameshiebert** [comment] 2017-01-03 20:02
OK, I've investigated a bit and I think the difference here is which method one uses to create a virtual environment. See [here](https://docs.python.org/3/library/venv.html#creating-virtual-environments) and [here](https://packaging.python.org/installing/#creating-virtual-environments) for reference. But it seems that using the old `virtualenv` script, that test will fail, while using the newer ``pyvenv`` and the newest ``python -m venv /path/to/venv``, the test succeeds.

I would hypothesize that the old virtualenv does not handle namespace packages properly (especially given a conversation that I had with one of the virtualenv authors long ago where he asked why the heck Pydap used namespace packages since many people think that they're kind of a bad idea).

In any case, the old virtualenv script is only required for Python versions <= 2.6 which (I believe there is general consensus about) we're not going to support in the next release.

So, I think that I'm going to close this issue and recommend that you use [one of the newer methods](https://docs.python.org/3/library/venv.html#creating-virtual-environments) for creating virtual environments.

**Closed by jameshiebert** 2017-01-03 20:02 UTC
Labels: confirmed

**Comment by ghisvail** [comment] 2017-01-06 19:07
@jameshiebert I can reproduce the problem when using `python3 -m venv` on Debian Stretch (Python 3.5.2). This issue is still alive I am afraid.
