### ISSUE TITLE
Missing 'proxy' module

### ISSUE THREAD

**Issue by giumas** [pydap/pydap#66] opened 2017-02-22 04:11 UTC
While attempting to run [HDFCompass](https://github.com/HDFGroup/hdf-compass) with the last PyPI release (3.2.0) of `pydap`, I noticed that the `proxy` module is gone together with `ProxyArray` class. Can you confirm it? If yes, is `BaseType` class the 'natural' substitute of `ProxyArray`?

The `ProxyArray` was imported here: https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/opendap_model/model.py#L19

**Comment by jameshiebert** [comment] 2017-02-22 17:58
It looks like @robertodealmeida replaced the ``proxy`` module during a refactoring in commits bc064513b7d6c173b9000df6985984164e168c57 and 92ed74bfef36940b39dd8900f161cb9f09b77184. It kind of looks like you can use [``BaseProxy``](https://github.com/pydap/pydap/blob/master/src/pydap/handlers/dap.py#L98) and [``SequenceProxy``](https://github.com/pydap/pydap/blob/master/src/pydap/handlers/dap.py#L202) to similar ends...

We should probably decide whether that's actually intended to be a public API, and if so, update the developer docs to reflect it.

**Comment by giumas** [comment] 2017-02-23 01:28
Thank you for the quick answer! However, from a first look, it seems that there are much more changes that just this class. 

For instance, the `DatasetType` does not more indirectly inherit from `odict`. Thus, the app fails when it tries to call the missing `setdefault` method (`AttributeError: '<class 'pydap.model.DatasetType'>' object has no attribute 'setdefault'`).

**Comment by laliberte** [comment] 2017-04-19 16:07
@giumas I've looked at your code and my opinion is that ``pydap`` proxy objects should not be assumed to be part of the public API. The obvious solution would be to rely only on the ``DatasetType`` object output from the ``open_url()`` function. If the function exits successfully, this object should contain all of the OPeNDAP dataset attributes and properly instantiated data proxy objects.

Moreover, it would seem to me that the easiest fix would be change https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/opendap_model/model.py#L235 to
```
self._data = new_dset[new_key].data
```
and line https://github.com/HDFGroup/hdf-compass/blob/develop/hdf_compass/opendap_model/model.py#L214-L215 should probably be removed.

**Comment by jameshiebert** [comment] 2017-05-22 15:44
@giumas are you satisfied with @laliberte's suggestions as a resolution to your issue? If so we can close this and just update the developer docs.

**Comment by jameshiebert** [comment] 2017-05-22 15:51
>  just update the developer docs

Nevermind, we have [that covered already](https://github.com/pydap/pydap/commit/4207286bc173dc9971eedd5508c41878e18cf1aa)

**Comment by giumas** [comment] 2017-05-22 16:40
@jameshiebert My apologies for not getting back on this! I am currently working on stuff quite far from HDF Compass. 

@jreadey Do you have time to give a look if the proposed solution fits the HDF Compass needs?

**Comment by jreadey** [comment] 2017-05-24 00:22
@giumas - it looks fine as far as I can see.  What this fix resolve https://github.com/HDFGroup/hdf-compass/issues/186? 
If you have time to do the update, that would be great.

**Comment by jameshiebert** [comment] 2017-05-24 04:49
OK, I'll go ahead and close then. Glad we got it figured out! :)

**Closed by jameshiebert** 2017-05-24 04:49 UTC

**Comment by giumas** [comment] 2017-07-01 00:15
> it looks fine as far as I can see

@jreadey Does it mean that you actually tested it? It does not seem that [the two proposed changes](https://github.com/HDFGroup/hdf-compass/commit/064a7a938199c2c53392e20ef35bf22db297cb39) are enough, at least on Windows. 

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\pydap\model.py", line 382, in __getattr__
    return self[attr]
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\pydap\model.py", line 425, in __getitem__
    return self._getitem_string(key)
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\pydap\model.py", line 404, in _getitem_string
    return self._dict[quote(key)]
KeyError: 'setdefault'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\pydap\model.py", line 235, in __getattr__
    return self.attributes[attr]
KeyError: 'setdefault'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\code\test\hdf-compass\hdf_compass\compass_viewer\frame.py", line 220, in on_resource_open
    self.open_url(url)
  File "c:\code\test\hdf-compass\hdf_compass\compass_viewer\frame.py", line 225, in open_url
    if can_open_store(url):
  File "c:\code\test\hdf-compass\hdf_compass\compass_viewer\viewer.py", line 175, in can_open_store
    instance = stores[0](url)
  File "c:\code\test\hdf-compass\hdf_compass\opendap_model\model.py", line 68, in __init__
    self._dataset.setdefault('')
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\pydap\model.py", line 384, in __getattr__
    return DapType.__getattr__(self, attr)
  File "C:\Users\user\AppData\Local\HyOc\py3\x64\lib\site-packages\pydap\model.py", line 239, in __getattr__
    % (type(self), attr))
AttributeError: '<class 'pydap.model.DatasetType'>' object has no attribute 'setdefault'
```

But I am not familiar with `pydap`. Who wrote the `pydad` plugin for HDF Compass?

**Comment by jreadey** [comment] 2017-07-03 05:21
@giumas, no I haven't had a chance to try it out.

We had an intern (3 years ago!) who wrote the PyDap plugin.

**Comment by ax3l** [comment] 2018-02-16 00:23
@giumas @laliberte @jameshiebert @jreadey the issue is not solved. Can you please re-open this issue and take a second look?
I tried to debug it and could not solve it either - although I have 0 knowledge on pydap...

**Comment by ax3l** [comment] 2018-02-16 00:24
This is the last backend that is missing to ship the `py3` branch for a new release, afaik.
