### ISSUE TITLE
"This is redirect error" when accessing NASA OPeNDAP HDF5 files (3.3.0)

### ISSUE THREAD

**Issue by battistowx** [pydap/pydap#284] opened 2023-06-06 19:24 UTC
Hello,

I'm attempting to use the Pydap setup_session(), open_url(), and PydapDataStore methods on two different OPeNDAP HDF5 files with Pydap 3.3.0 and Python 3.9.12. I use those methods to load them with my URS credentials successfully, and I'm able to view each key:

```
opendap_url = 'https://oco2.gesdisc.eosdis.nasa.gov/opendap/OCO2_L1B_Science.10r/2015/015/oco2_L1bScND_02865a_150114_B10003r_191222121514.h5'
session = setup_session("my_username", "my_password", check_url=opendap_url)
dataset = open_url(opendap_url, session=session)

store = xr.backends.PydapDataStore.open(opendap_url, session=session)
ds = xr.open_dataset(store)
```

However, when I attempt to view the data itself by calling the values of one of those keys (such as `dataset['SoundingGeometry_sounding_longitude'].data[:]`, or when attempting to view the Xarray dataset, I am met with the following error:

```
Found

The document has moved [here](https://urs.earthdata.nasa.gov/oauth/authorize/?scope=uid&app_type=401&client_id=e2WVk8Pw6weeLUKZYOxvTQ&response_type=code&redirect_uri=https%3A%2F%2Fgpm1.gesdisc.eosdis.nasa.gov%2Fdata-redirect&state=aHR0cHM6Ly9ncG0xLmdlc2Rpc2MuZW9zZGlzLm5hc2EuZ292L29wZW5kYXAvR1BNX0wzL0dQTV8zSU1FUkdISC4wNi8yMDAwLzE1My8zQi1ISFIuTVMuTVJHLjNJTUVSRy4yMDAwMDYwMS1TMDAwMDAwLUUwMDI5NTkuMDAwMC5WMDZCLkhERjUuZG9kcz90aW1lX2JuZHMlNUIwOjE6MCU1RCU1QjA6MTowJTVE).


This is redirect error. These should not usually raise an error in pydap beacuse redirects are handled implicitly. If it failed it is likely due to a circular redirect.
```

The error also occurs with this file: https://gpm1.gesdisc.eosdis.nasa.gov/opendap/GPM_L3/GPM_3IMERGHH.06/2000/153/3B-HHR.MS.MRG.3IMERG.20000601-S000000-E002959.0000.V06B.HDF5, but it works just fine with native NetCDF4 files, such as this one: https://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/1980/01/MERRA2_100.tavg1_2d_slv_Nx.19800101.nc4

Could this be due to an issue with HDF5 files not being handled correctly by Pydap, or could it be an authentication issue?

Thank you!

**Comment by ndp-opendap** [comment] 2023-06-06 21:00
You might review these tutorials and see if what you're doing to set up the session chimes with how these describe the approach:

- [Client Authentication (PyDAP)](https://opendap.github.io/documentation/tutorials/ClientAuthentication.html#_pydap)
- [PyDAP with DAP2](https://github.com/OPENDAP/notebooks/blob/master/tutorials/pydap_dap2_basic.ipynb)
- [PyDAP with DAP4](https://github.com/OPENDAP/notebooks/blob/master/tutorials/pydap_dap4_basic.ipynb) _We recently release an updated PyDAP (3.4.x) with updated DAP4 support - it should be available in PIP now._

**Comment by battistowx** [comment] 2023-06-06 22:10
I've generated a netrc and dodsrc files, then followed the open_url step (without protocol="dap4") in [Client Authentication (PyDAP)](https://opendap.github.io/documentation/tutorials/ClientAuthentication.html#_pydap) and replaced the URL in the [DAP2](https://github.com/OPENDAP/notebooks/blob/master/tutorials/pydap_dap2_basic.ipynb) tutorial, but the error still occurs even after installing 3.4.0 (this is using a DAP2 Hyrax server). It's still working as normal for the MERRA2 NetCDF4 file.

One thing I noticed is that although it appears to load the metadata correctly without issues, and I'm able to view the shapes of the dimensions, every variable contains "FakeDim" pseudo Maps, like below:

```
Dataset {
    Float32 FootprintGeometry_footprint_altitude[FakeDim0 = 8364][FakeDim1 = 8][FakeDim2 = 3];
    Float32 FootprintGeometry_footprint_altitude_uncert[FakeDim0 = 8364][FakeDim1 = 8][FakeDim2 = 3];
    Float32 FootprintGeometry_footprint_aspect[FakeDim0 = 8364][FakeDim1 = 8][FakeDim2 = 3];
    Float32 FootprintGeometry_footprint_azimuth[FakeDim0 = 8364][FakeDim1 = 8][FakeDim2 = 3];
    Float32 FootprintGeometry_footprint_land_fraction[FakeDim0 = 8364][FakeDim1 = 8][FakeDim2 = 3];
    ......
```

That's not the case for the GPM granule-although that and MERRA-2 are not L1B like the OCO granule is.

**Comment by battistowx** [comment] 2023-07-24 21:10
Hello,

Brief update on where we are at with this error:

It looks like it is still occurring with 3.4.0 and 3.4.1 on our on-premises OPeNDAP servers, including the one originally listed. However, on some of the servers, I am receiving a `UserWarning: password was not set. this was likely unintentional but will result is much fewer datasets.` error, followed by the same redirect error when attempting to access the values. The metadata is still successfully loading, however.

This is occurring when attempting to run the following code with 3.4.1, and on the disc2 server with a different granule:

```
from pydap.client import open_url
from pydap.cas.get_cookies import setup_session

dataset_url = 'https://disc2.gesdisc.eosdis.nasa.gov/opendap/MERGED_IR/GPM_MERGIR.1/2016/224/merg_2016081100_4km-pixel.nc4'

username = 'my_username'
password = 'my_password'

try:
    session = setup_session(username, password, check_url=dataset_url)
    dataset = open_url(dataset_url, session=session)
except AttributeError as e:
    print('Error:', e)
    print('Please verify that the dataset URL points to an OPeNDAP server, the OPeNDAP server is accessible, or that your username and password are correct.')
```

I have verified that the EDL username is correct by accessing that same granule successfully with Xarray.

**Comment by Mikejmnez** [comment] 2024-03-30 00:07
Hi, just looking into this now and I can confirm that the `redirect` issue involving the hfd5 datasets remains. BTW I ran the code above in the last comment and ran just fine (with my own credentials).  The only difference being that I use ```from pydap.cas.urs import setup_session```

> I have verified that the EDL username is correct by accessing that same granule successfully with Xarray.

hmm, intriguing. I am certain that `xarray` is explicitly using `pydap.client.open_url` and passing along the session argument to open OPeNDAP datasets. But that is the nc4 file so no issue there...

> One thing I noticed is that although it appears to load the metadata correctly without issues, and I'm able to view the shapes of the dimensions, every variable contains "FakeDim" pseudo Maps, like below:

Indeed. You can see those "FakeDims" from the [html](https://oco2.gesdisc.eosdis.nasa.gov/opendap/OCO2_L1B_Science.10r/2015/015/oco2_L1bScND_02865a_150114_B10003r_191222121514.h5.html) opendap access form. I wonder if that is because this is level 1 data...

Anyways, I will look at this when I have a bit more time...

**Comment by Mikejmnez** [comment] 2024-04-02 22:44
Thanks to @ndp-opendap that shared this resource with me on how to [Use EDL authorization tokens for data access](https://opendap.github.io/documentation/tutorials/ClientAuthenticationWithEDLTokens.html) I can confirm that the issue was authentication. 

**<ins>NOTE</ins>**: When following the steps in the link above to use EDL tokens with pydap (hence xarray), there is a typo. When defining the sessions do this instead:

```python
import requests
from pydap.client import open_url

my_session = requests.Session()
my_session.headers={"Authorization": auth_hdr} # ----typo here---- this should a dictionary!
```

Then the following works with both hdf5 files, albeit rather slow
```python
dataset = open_url(dataset_url, session=my_session)
```

I can even load data using pydap.

#### with file `/3B-HHR.MS.MRG.3IMERG.20000601-S000000-E002959.0000.V06B.HDF5` :
```python
$ dataset['latv'][:].data
>>> array([0, 1], dtype='>i4')
```


#### with file `oco2_L1bScND_02865a_150114_B10003r_191222121514.h5` :
```python
$ dataset['SoundingGeometry_sounding_longitude'][:].data
>>> array([[ -9.377283,  -9.338884,  -9.300327, ...,  -9.185181,  -9.146923,
         -9.108694],
       [ -9.415196,  -9.376762,  -9.338172, ...,  -9.222924,  -9.184633,
         -9.146371],
       [ -9.453184,  -9.414717,  -9.376092, ...,  -9.26073 ,  -9.22239 ,
         -9.184079],
       ...,
       [171.62787 , 171.6523  , 171.67685 , ..., 171.75017 , 171.77454 ,
        171.79887 ],
       [171.6118  , 171.63625 , 171.66081 , ..., 171.73419 , 171.75856 ,
        171.78291 ],
       [171.5957  , 171.62018 , 171.64476 , ..., 171.71819 , 171.74258 ,
        171.76695 ]], dtype='>f4')
```

**Comment by Mikejmnez** [comment] 2024-04-04 17:22
Will close this issue as completed. Feel free to re-open if the problem persists.

**Closed by Mikejmnez** 2024-04-04 17:22 UTC

**Comment by battistowx** [comment] 2024-04-04 20:07
That's fantastic, thank you so much for investigating this! I figured it would be an EDL-related issue...and I'm wondering why it won't accept the local credential files. We are currently beginning to advise users to use tokens more, and I will see if I can add those steps to our existing documentation at GES DISC!
