### ISSUE TITLE
pip3 install pydap.responses.netcdf gives error

### ISSUE THREAD

**Issue by Omkar20895** [pydap/pydap#70] opened 2017-02-28 07:15 UTC
- The error is as follows : 

Collecting pydap.responses.netcdf
  Downloading pydap.responses.netcdf-0.1.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-90qbdmot/pydap.responses.netcdf/setup.py", line 10, in <module>
        paver.tasks.main()
      File "/usr/local/lib/python3.5/dist-packages/paver/tasks.py", line 878, in main
        _launch_pavement(args)
      File "/usr/local/lib/python3.5/dist-packages/paver/tasks.py", line 846, in _launch_pavement
        exec(compile(source, environment.pavement_file, 'exec'), mod.__dict__)
      File "pavement.py", line 23, in <module>
        classifiers=filter(None, map(string.strip, '''
    AttributeError: module 'string' has no attribute 'strip'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-90qbdmot/pydap.responses.netcdf/

**Comment by lewismc** [comment] 2017-02-28 07:48
It would appear that the pydap.responses.netcdf package may need a bit of attention here. Does anyone know where the canonical source for it lives?
I've spotted both of the following
 * https://bitbucket.org/robertodealmeida/pydap/src/6feb1fc58d19/pydap.handlers.netcdf/?at=default
 * https://github.com/pacificclimate/pydap.responses.netcdf

The [package over at Pypi](https://pypi.python.org/pypi/pydap.responses.netcdf) would indicate the the first location above is the correct location as the author is @robertodealmeida. Can you please clarify @robertodealmeida ?

**Comment by lewismc** [comment] 2017-02-28 07:49
Also @Omkar20895 it looks like the package on Pypi is built for Python 2.7 rather than 3.X. We may need to upgrade this...

**Comment by Omkar20895** [comment] 2017-03-01 19:09
@lewismc The first source you have mentioned is for pydap.handlers and the second one is for pydap.responses, we are specifically focusing on pydap.responses here. 

And yes according to the version [here](https://pypi.python.org/pypi/pydap.responses.netcdf/0.1.4.1) the package is for python2.7 and it needs to be upgraded.

**Comment by lewismc** [comment] 2017-03-01 20:27
@Omkar20895 see https://github.com/pacificclimate/pydap.responses.netcdf/issues/3

**Comment by lewismc** [comment] 2017-04-20 00:33
@Omkar20895 having spoken with @robertodealmeida it turns out that the most recent version of the **pydap.responses.netcdf** library can be found [here](https://bitbucket.org/robertodealmeida/pydap/src/6feb1fc58d19718c563289780e3eb4fa9e185a18/pydap.responses.netcdf/?at=default). 

I had to manually install [Pupynere](https://bitbucket.org/robertodealmeida/pupynere/) against Python 3 with the following patch
```
$ hg remove pavement.py
$ python setup.py install
```
I was then able to build pydap.responses.netcdf with ```python setup.py install```

**Comment by lewismc** [comment] 2017-04-20 00:38
Once you get to the stage above, can we both attempt addressing https://github.com/nasa/podaacpy/issues/101 ? Let me know when you read this and have got this far. We can then look again at addressing http://www.pydap.org/en/latest/responses.html#netcdf

**Comment by jameshiebert** [comment] 2017-05-22 15:32
Hi all, I'm going to close this issue as a psudo-duplicate of #39 Further discussion can be directed in that direction.

**Closed by jameshiebert** 2017-05-22 15:32 UTC
