### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by nathanlcarlson** [pydap/pydap#202] opened 2019-07-30 22:24 UTC
As reported in the pydap.org repository https://github.com/pydap/pydap.org/issues/1 it appears the pydap.org site is unavailable.

**Comment by neishm** [comment] 2019-07-31 02:43
Looks like this issue is already reported in #169.  The alternate URL https://www.pydap.org still works.

**Comment by nathanlcarlson** [comment] 2019-07-31 02:45
Okay, should probably put that one in the header line at the top of this repository.

**Comment by tomkralidis** [comment] 2019-09-20 09:05
Closing as duplicate of #169.  The pydap/pydap.org repository is since deleted given we kept the website setup in pydap/pydap proper.

**Closed by tomkralidis** 2019-09-20 09:05 UTC
