### ISSUE TITLE
ValueError when trying to access data from thredds.met.no

### ISSUE THREAD

**Issue by a-schneider-fmi** [pydap/pydap#263] opened 2022-05-13 06:57 UTC
Trying to access a subset of data from a dataset at thredds.met.no, a ValueError (buffer size must be a multiple of element size) occurs with pydap version 3.3.0 or the latest version from the master branch. This can be reproduced as follows:
```
>>> from pydap.client import open_url
>>> import numpy as np
>>> ds = open_url('https://thredds.met.no/thredds/dodsC/mepslatest/meps_lagged_6_h_latest_2_5km_latest.nc')
>>> print(ds.x_wind_pl.dimensions)
('time', 'pressure', 'ensemble_member', 'y', 'x')
>>> print(ds.x_wind_pl.shape)
(62, 2, 30, 1069, 949)
>>> ux = ds.x_wind_pl[0, 0, 0, 10:20, 20:30]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydap/src/pydap/model.py", line 746, in __getitem__
    var.data = self[var.name].data[slice_]
  File "pydap/src/pydap/handlers/dap.py", line 175, in __getitem__
    dataset.data = unpack_data(BytesReader(data), dataset)
  File "pydap/src/pydap/handlers/dap.py", line 452, in unpack_data
    return unpack_children(xdr_stream, dataset)
  File "pydap/src/pydap/handlers/dap.py", line 383, in unpack_children
    out.append(tuple(unpack_children(stream, col)))
  File "pydap/src/pydap/handlers/dap.py", line 387, in unpack_children
    out.extend(convert_stream_to_list(stream, col.dtype, col.shape,
  File "pydap/src/pydap/handlers/dap.py", line 413, in convert_stream_to_list
    np.frombuffer(
ValueError: buffer size must be a multiple of element size

```
As pointed out by met.no's helpdesk, the data can be accessed with curl asking for ASCII output
```
curl -v https://thredds.met.no/thredds/dodsC/mepslatest/meps_lagged_6_h_latest_2_5km_latest.nc.ascii?x_wind_pl%5B0:1:0%5D%5B0:1:0%5D%5B0:1:0%5D%5B10:1:20%5D%5B20:1:30%5D
```
which indicates that the problem lies on pydap's side.

**Comment by DanCodigaMWRA** [comment] 2022-10-17 20:31
I can reproduce this error. 
And it seems similar to or same as the question I just posted: #273.
Might also be related to #218 @jondoesntgit ?

**Comment by nicodebo** [comment] 2023-01-06 14:37
I don't really understand why but opening the dataset like herebelow seems to fix the issue:
`ds = open_url('https://thredds.met.no/thredds/dodsC/mepslatest/meps_lagged_6_h_latest_2_5km_latest.nc', output_grid=False)`
There is a custom error message with a hint in the source code (dap.py) but for some reason it is not triggered.

**Comment by Mikejmnez** [comment] 2024-04-03 00:12
My understanding is that this is a standard behavior of the DAP2 protocol (and one of the major difference with the DAP4). -pydap for the most part implements the dap2. 

To correctly slice the variable `x_wind_pl` one has to do:

```python
ds = open_url('https://thredds.met.no/thredds/dodsC/mepslatest/meps_lagged_6_h_latest_2_5km_latest.nc')
ux = ds['x_wind_pl']['x_wind_pl'][0, 0, 0, 10:20, 20:30]
```
(Notice the extra brackets). It is because `x_wind_pl` is a GridType which contains an extra layer of abstraction. You can see this with:
```python
ds['x_wind_pl']
>>> <GridType with array 'x_wind_pl' and maps 'time', 'pressure', 'ensemble_member', 'y', 'x'>
```
and so to access directly the data var 'x_wind_pl' one must go the extra layer: `ds['x_wind_pl']['x_wind_pl']`. And by setting `output_grid=False`,`open_url` does not create that extra layer of abstraction.

Thanks for opening the issue in the first place! To bad it took too long for somebody to take a look. I will close this issue but feel free to re-open if needed.

**Closed by Mikejmnez** 2024-04-03 00:12 UTC
