### ISSUE TITLE
Support for DAP4 objects in PyDAP python library

### ISSUE THREAD

**Issue by jgallagher59701** [pydap/pydap#299] opened 2024-03-27 18:11 UTC
There have been a few errors reported recently when attempting to open an Earthdata Cloud Hyrax URL using PyDAP: 

1. Chris Lynnes reported an error in #opendap-support on 12/14/21 from this code:

```
import xarray as xr
url = "https://opendap.earthdata.nasa.gov/providers/POCLOUD/collections/ECCO%20Ocean%20Temperature%20and%20Salinity%20-%20Monthly%20Mean%200.5%20Degree%20(Version%204%20Release%204)/granules/OCEAN_TEMPERATURE_SALINITY_mon_mean_2017-12_ECCO_V4r4_latlon_0p50deg
"
ds = xr.open_dataset(url)
```
 
2. ORNL developed a jupyter notebook that also reports an error using PyDAP and xarray: 

https://github.com/michele-personal/earthdata_hyraxOPeNDAP_access/blob/main/DaymetV4_access_subsetting_HyraxError.ipynb

James Gallagher mentioned that PyDAP needs to be expanded to support DAP4 objects which may explain the errors in either/both cases. From ORNL's perspective, this is close to a blocking issue so we need to make sure this is being addressed to fully support ORNL users.

**Comment by Mikejmnez** [comment] 2024-03-27 23:29
# Case 1: ECCO data access

Noting wrong. I was able to make some plots which means decoding also works well within xarray. I see that the issue is from <ins>2021</ins> so pretty old, which explains why I had to modify the code slightly. Here is is

```python
import xarray as xr
import matplotlib.pyplot as plt
from pydap.client import open_url
from pydap.cas.urs import setup_session

# create credentials to access data
username = "_Username_here_" 
password= "_password_here_"
hyrax_url = 'https://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/'
session = setup_session(username, password, check_url=hyrax_url)

# access data via xarray
# ECCO url
url = "https://opendap.earthdata.nasa.gov/providers/POCLOUD/collections/ECCO%20Ocean%20Temperature%20and%20Salinity%20-%20Monthly%20Mean%200.5%20Degree%20(Version%204%20Release%204)/granules/OCEAN_TEMPERATURE_SALINITY_mon_mean_2017-12_ECCO_V4r4_latlon_0p50deg"

# access to single dataset via xarray
ds = xr.open_dataset(url, engine='pydap', session=session)


# plot  fields to verify decoding works or data not corrupted
# xarray triggers calculations/download when making a plot

fig, axes = plt.subplots(1, 2, figsize=(14, 4))
ds['SALT'].isel(time=0, Z=0).plot(ax=axes[0])
ds['THETA'].isel(time=0, Z=0).plot(ax=axes[1])
plt.show()

```
I get: 

![Screenshot 2024-03-27 at 4 28 22 PM](https://github.com/pydap/pydap/assets/8241481/25e25adb-3844-4167-809e-4a79b3f1d055)

**Comment by Mikejmnez** [comment] 2024-03-28 06:10
# case 2

The notebooks are a little bit old, using `xarray = 2023.3` and `python =3.9`. However, from a quick inspection it is clear to me that the issue takes place with `xarray` when decoding variables, rather than when  `pydap` accesses a remote data via the url.

### Below is my assessment of the three notebooks.

I followed the link to three notebooks:
1. Notebook [DaymetV4_access_subsetting_HyraxError.ipynb](https://github.com/michele-personal/earthdata_hyraxOPeNDAP_access/blob/main/DaymetV4_access_subsetting_HyraxError.ipynb). The error is on cel [15], when trying to open the file with url:

```python
url = "http://opendap.earthdata.nasa.gov/collections/C2031536952-ORNL_CLOUD/granules/Daymet_Daily_V4.daymet_v4_daily_na_prcp_2010.nc"
```
**Result:** I think the file is no longer there. I tried opening it with pydap and kept getting:
```python
open_url(url, session=session) # session defined from EarthData username, password and hyrax url
>>>
HTTPError: 404 Not Found
Error { 
    code = 404;
    message = "The specified path 'collections[/C2031536952-ORNL_CLOUD/granules/Daymet_Daily_V4.daymet_v4_daily_na_prcp_2010.nc](http://localhost:8888/C2031536952-ORNL_CLOUD/granules/Daymet_Daily_V4.daymet_v4_daily_na_prcp_2010.nc)' does not identify a granule in CMR.";
}
```

Because the file is no longer there, <ins>I could not reproduce the error</ins>, nor diagnose what is going on. However, the error takes place when trying to create an xarray.dataset object and now in the step before where pydap accesses the dataset via the url. And so my guess is that is has to do with the decoding of the dimensions and not with pydap's functionality.

2. Notebook [DaymetV4_access_subsetting_NGAP_Hyrax_OPeNDAP_Cali.ipynb](https://github.com/michele-personal/earthdata_hyraxOPeNDAP_access/blob/main/DaymetV4_access_subsetting_NGAP_Hyrax_OPeNDAP_Cali.ipynb).
**Result**: No errors, <ins>runs fine</ins>.


3. Notebook [DaymetV4_NGAP_Hyrax_OPeNDAP.ipynb](https://github.com/michele-personal/earthdata_hyraxOPeNDAP_access/blob/main/DaymetV4_NGAP_Hyrax_OPeNDAP.ipynb).

**Results** 
I am using a slightly newer version of xarray (`24.2.0`, most recent stable release) and so I cannot reproduce the same error (unless i downgrade xarray to an older version). But the fact that there continue to be errors is not desirable. Below is the description of the error I get with the newer version of xarray.


The issue shows up when trying to create an `xarray.Dataset`. `pydap` is able to read the file just fine. The file in hand is: [Daymet_Daily_V4R1.daymet_v4_daily_na_tmax_2010.nc](https://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/Daymet_Daily_V4R1.daymet_v4_daily_na_tmax_2010.nc.html). 

In particular, the issue takes place when xarray tries to decoding the variable `time_bnds`. The example above illustrates this:

```python
# EarthData info here
username="_Username_here_"
passworrd="_password_here"

hyrax_url = 'https://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/'

session = setup_session(username, password, check_url=hyrax_url)  

granule_dap = hyrax_url + "Daymet_Daily_V4R1.daymet_v4_daily_na_tmax_2010.nc"

# this works:
hyrax_ds = pydap.client.open_url(granule_dap, session=session) # session tra
hyrax_ds
>>> <DatasetType with children 'y', 'lon', 'lat', 'time', 'x', 'tmax', 'lambert_conformal_conic', 'time_bnds', 'yearday'>
```
I can even make figures which means data is not corrupted.

<ins>HOWEVER</ins>, the following errs on the xarray side of things

```python
xr.open_dataset(granule_dap, engine="pydap", session=session)
```
with traceback:
```python
ValueError: dimensions ('time',) must have the same length as the number of data dimensions, ndim=2
```
The issue is clearly the variable 'time_bnds'. `xarray` is having some trouble decoding it. I think the error in the older version of xarray is related to this variable too. I know `time_bnds` is the issue because I can pass constrained expressions to the url to open a single variable. This is:

This works (`tmax` is the main variable of that dataset, `max temperature`):
```python
xr.open_dataset(granule_dap+'?tmax', engine="pydap", session=session)
```
but this fails:
```python
xr.open_dataset(granule_dap+'?time_bnds', engine="pydap", session=session)
```
In fact, I reproduce the error exactly. 


# solution:
I think there must be a workaround to the errors described above. I will continue to look tomorrow.

**Comment by Mikejmnez** [comment] 2024-03-29 17:24
I tried the solution above, which in theory should work. However,  I continue to have the same error which implies that `xarray` only drops the variable after creating the dataset. I will move this conversation to xarray to figure out the best way to allow `drop_variables` to act before attempting to create the`xarray.dataset`. with pydap as `backend`.

**Comment by Mikejmnez** [comment] 2024-03-29 23:21
# working solution :

All is needed it to add an extra line in both cases.

In notebook [DaymetV4_access_subsetting_HyraxError.ipynb](https://github.com/michele-personal/earthdata_hyraxOPeNDAP_access/blob/main/DaymetV4_access_subsetting_HyraxError.ipynb) cell [15] do:
```python
thredds_ds = open_url(granule_dap, session=session)
# extra line here to drop `time_bnds`
thredds_ds = thredds_ds[tuple([var for var in thredds_ds.keys() if var not in ['time_bnds']])]

ds = xr.open_dataset(xr.backends.PydapDataStore(thredds_ds), decode_coords="all")
```

In notebook [DaymetV4_NGAP_Hyrax_OPeNDAP.ipynb](https://github.com/michele-personal/earthdata_hyraxOPeNDAP_access/blob/main/DaymetV4_NGAP_Hyrax_OPeNDAP.ipynb) also add the extra line, so that in cell [19]:

```python
hyrax_ds = open_url(granule_dap, session=session)
# extra line here to drop `time_bnds`
hyrax_ds = hyrax_ds[tuple([var for var in hyrax_ds.keys() if var not in ['time_bnds']])]

ds = xr.open_dataset(xr.backends.PydapDataStore(hyrax_ds), decode_coords="all")
```


Will close this issue as I think it is solved.  Feel free to re-open

**Closed by Mikejmnez** 2024-03-29 23:21 UTC
